#!/usr/bin/env python3

# Generate a Word2vec model (to use for evaluating topic coherence)
# Jonathan Gordon, 2016-03-29

import sys
from gensim.models.word2vec import Word2Vec, LineSentence

if len(sys.argv) < 2:
    sys.stderr.write('Usage: gen-word2vec-model [corpus dir]\n')
    sys.exit()

sentences = LineSentence(sys.argv[1])

model = Word2Vec(sentences, size=50, window=10, negative=10, min_count=5,
                 iter=3, workers=4, sg=0)
model.init_sims(replace=True)

model.save_word2vec_format('word2vec-model.bin', binary=True)
