#!/usr/bin/env python3

import sys
import json

from t.corpus import Corpus, Document

c = Corpus()
c.load(sys.argv[1])

j = {}
for doc in c:
    j[doc.id] = {'title': doc.title,
                 'author': '; '.join(doc.authors)}

print(json.dumps(j))
