#!/usr/bin/env python3

# Produce a metadata index JSON file from a corpus
# Jonathan Gordon, 2016-02-19

import sys
import json

from t.corpus import Corpus, Document

# It's 2016 and writing Unicode is still a hack.
sys.stdout = open(sys.stdout.fileno(), mode='w', encoding='utf8', buffering=1)

c = Corpus()
c.load(sys.argv[1])

j = {}
for doc in c:
    j[doc.id] = {'title': doc.title,
                 'author': '; '.join(doc.authors),
                 'year': doc.year,
                 'book': doc.book,
                 'url': doc.url}

sys.stdout.write(json.dumps(j, ensure_ascii=False))
