#!/usr/bin/env python3

# Generate a JSON document containing the contents of a text file.
# Metadata needs to be added manually.

import sys

from techknacq.lx import SentTokenizer
from techknacq.corpus import Corpus, Document

st = SentTokenizer()

d = Document()
d.sections = [{'text': st.tokenize(open(sys.argv[1]).read())}]

c = Corpus()
c.add(d)
c.fix_text()

c.export(sys.argv[2])
